name: CI tests
on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.13.x
          - 1.14.x
          - 1.15.x
        os:
          - ubuntu-18.04
          - ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Go dependencies
        run: |
          go mod init github.com/lxc/distrobuilder
          go get github.com/mudler/docker-companion/api@master
          go get -t -d ./...

      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y squashfs-tools

      - name: Test
        run: make check
